var enemys_fcae963b_31c9_42b4_b48c_bb48d09f3f80 = 
{
	"greenSlime": {"name":"绿头怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[28]},
	"redSlime": {"name":"红头怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[16,18],"value":10},
	"blackSlime": {"name":"青头怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"slimelord": {"name":"怪王","hp":100,"atk":120,"def":0,"money":10,"exp":0,"point":0,"special":[1,9]},
	"bat": {"name":"小蝙蝠","hp":100,"atk":120,"def":0,"money":2,"exp":0,"point":0,"special":[1]},
	"bigBat": {"name":"大蝙蝠","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"redBat": {"name":"红蝙蝠","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[]},
	"vampire": {"name":"冥灵魔王","hp":888,"atk":888,"def":888,"money":888,"exp":888,"point":0,"special":[6],"n":8},
	"skeleton": {"name":"骷髅人","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"skeletonCaptain": {"name":"骷髅队长","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"zombie": {"name":"兽人","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"zombieKnight": {"name":"兽人武士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"rock": {"name":"石头人","hp":50,"atk":50,"def":0,"money":3,"exp":0,"point":0,"special":3},
	"bluePriest": {"name":"初级法师","hp":100,"atk":120,"def":0,"money":3,"exp":0,"point":1,"special":[9]},
	"redPriest": {"name":"高级法师","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"brownWizard": {"name":"初级巫师","hp":100,"atk":120,"def":0,"money":16,"exp":0,"point":0,"special":15,"value":100,"range":2},
	"redWizard": {"name":"高级巫师","hp":1000,"atk":1200,"def":0,"money":160,"exp":0,"point":0,"special":15,"value":200,"zoneSquare":true},
	"swordsman": {"name":"双手剑士","hp":100,"atk":120,"def":0,"money":6,"exp":0,"point":0,"special":4},
	"soldier": {"name":"冥战士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"yellowKnight": {"name":"金骑士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"redKnight": {"name":"红骑士","hp":500,"atk":200,"def":50,"money":0,"exp":0,"point":0,"special":[7]},
	"darkKnight": {"name":"黑骑士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"blueKnight": {"name":"蓝骑士","hp":100,"atk":120,"def":0,"money":9,"exp":0,"point":0,"special":8},
	"goldSlime": {"name":"黄头怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"poisonSkeleton": {"name":"紫骷髅","hp":50,"atk":60,"def":70,"money":80,"exp":0,"point":0,"special":13},
	"poisonBat": {"name":"紫蝙蝠","hp":100,"atk":120,"def":0,"money":14,"exp":0,"point":0,"special":13},
	"skeletonPriest": {"name":"骷髅法师","hp":100,"atk":100,"def":0,"money":0,"exp":0,"point":0,"special":18,"value":20},
	"skeletonKing": {"name":"骷髅王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"evilHero": {"name":"迷失勇者","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"demonPriest": {"name":"魔神法师","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"goldHornSlime": {"name":"金角怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"silverSlime": {"name":"银头怪","hp":100,"atk":120,"def":0,"money":15,"exp":0,"point":0,"special":14},
	"whiteHornSlime": {"name":"尖角怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"redSwordsman": {"name":"剑王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[]},
	"poisonZombie": {"name":"绿兽人","hp":100,"atk":120,"def":0,"money":13,"exp":0,"point":0,"special":[12]},
	"octopus": {"name":"血影","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0,"bigImage":"dragon_1.png"},
	"princessEnemy": {"name":"假公主","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"angel": {"name":"天使","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"elemental": {"name":"元素生物","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"steelGuard": {"name":"铁守卫","hp":50,"atk":50,"def":50,"money":0,"exp":0,"point":0,"special":[18],"value":20},
	"evilBat": {"name":"邪恶蝙蝠","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"silverSlimelord": {"name":"银怪王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"goldSlimelord": {"name":"金怪王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"skeletonWarrior": {"name":"骷髅士兵","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"whiteSlimeman": {"name":"水银战士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"slimeman": {"name":"影子战士","hp":100,"atk":0,"def":0,"money":11,"exp":0,"point":0,"special":[9],"atkValue":2,"defValue":3},
	"yellowGateKeeper": {"name":"初级卫兵","hp":100,"atk":120,"def":0,"money":10,"exp":0,"point":0,"special":0},
	"blueGateKeeper": {"name":"中级卫兵","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"redGateKeeper": {"name":"高级卫兵","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"magicMaster": {"name":"黑暗大法师","hp":100,"atk":120,"def":0,"money":12,"exp":0,"point":0,"special":11,"value":0.3333333333333333,"add":true,"notBomb":true},
	"devilWarrior": {"name":"魔神武士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"fairyEnemy": {"name":"仙子","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"dragon": {"name":"魔龙","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0,"bigImage":"dragon_0.png"},
	"skeletonKnight": {"name":"骷髅武士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"skeletonPresbyter": {"name":"骷髅巫师","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"ironRock": {"name":"铁面人","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"grayRock": {"name":"灰色石头人","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"yellowPriest": {"name":"中级法师","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"evilPrincess": {"name":"痛苦魔女","hp":1000,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[10]},
	"blademaster": {"name":"剑圣","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"evilFairy": {"name":"黑暗仙子","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"greenKnight": {"name":"强盾骑士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"bowman": {"name":"初级弓兵","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"watcherSlime": {"name":"邪眼怪","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"devilKnight": {"name":"恶灵骑士","hp":150,"atk":100,"def":50,"money":0,"exp":0,"point":0,"special":[1,5,7,8]},
	"grayPriest": {"name":"混沌法师","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"greenGateKeeper": {"name":"卫兵队长","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"ghostSoldier": {"name":"冥队长","hp":200,"atk":100,"def":50,"money":0,"exp":0,"point":0,"special":8},
	"frostBat": {"name":"寒蝙蝠","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"blackKing": {"name":"黑衣魔王","hp":1000,"atk":500,"def":0,"money":1000,"exp":1000,"point":0,"special":0,"notBomb":true},
	"yellowKing": {"name":"黄衣魔王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"greenKing": {"name":"青衣武士","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"redKing": {"name":"红衣魔王","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"blueKing": {"name":"白衣武士","hp":100,"atk":120,"def":0,"money":17,"exp":0,"point":0,"special":16},
	"keiskeiFairy": {"name":"铃兰花妖","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"tulipFairy": {"name":"郁金香花妖","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"purpleBowman": {"name":"高级弓兵","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":0},
	"bearDown": {"name":"熊出没","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[],"faceIds":{"down":"bearDown","left":"bearLeft","right":"bearRight","up":"bearUp"},"bigImage":"bear.png"},
	"bearLeft": {"name":"熊出没","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[],"faceIds":{"down":"bearDown","left":"bearLeft","right":"bearRight","up":"bearUp"}},
	"bearRight": {"name":"熊出没","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[],"faceIds":{"down":"bearDown","left":"bearLeft","right":"bearRight","up":"bearUp"}},
	"bearUp": {"name":"熊出没","hp":0,"atk":0,"def":0,"money":0,"exp":0,"point":0,"special":[],"faceIds":{"down":"bearDown","left":"bearLeft","right":"bearRight","up":"bearUp"}},
	"e1": {"name": "小小玉", "hp": 55, "atk": 6, "def": 0, "money": 0, "exp": 1, "point": 0, "special": [],"bigImage":"enemy_e1.png"},
	"e107": {"name": "无我梦中", "hp": 90, "atk": 40, "def": 0, "money": 0, "exp": 9, "point": 0, "special": 2,"bigImage":"enemy_e107.png"},
	"e126": {"name": "石怪", "hp": 25, "atk": 9, "def": 0, "money": 0, "exp": 2, "point": 0, "special": 3,"bigImage":"enemy_e126.png"},
	"e127": {"name": "濑", "hp": 125, "atk": 19, "def": 2, "money": 0, "exp": 4, "point": 0, "special": [47],"bigImage":"enemy_e127.png"},
	"e146": {"name": "白菫影", "hp": 90, "atk": 18, "def": 1, "money": 0, "exp": 3, "point": 0, "special": [44],"bigImage":"enemy_e146.png"},
	"e158": {"name": "付丧", "hp": 70, "atk": 11, "def": 1, "money": 0, "exp": 2, "point": 0, "special": [29],"bigImage":"enemy_e158.png"},
	"e159": {"name": "怨灵华", "hp": 49, "atk": 17, "def": 2, "money": 0, "exp": 3, "point": 0, "special": [],"bigImage":"enemy_e159.png"},
	"e160": {"name": "付丧鬼", "hp": 75, "atk": 19, "def": 3, "money": 0, "exp": 4, "point": 0, "special": [29],"bigImage":"enemy_e160.png"},
	"e161": {"name": "古付丧鬼", "hp": 90, "atk": 21, "def": 4, "money": 0, "exp": 5, "point": 0, "special": [29],"bigImage":"enemy_e161.png"},
	"e162": {"name": "夜来丧", "hp": 145, "atk": 22, "def": 5, "money": 0, "exp": 6, "point": 0, "special": [],"bigImage":"enemy_e162.png"},
	"e163": {"name": "饿血华", "hp": 16, "atk": 19, "def": 2, "money": 0, "exp": 3, "point": 0, "special": [],"bigImage":"enemy_e163.png"},
	"e164": {"name": "古付丧", "hp": 99, "atk": 13, "def": 1, "money": 0, "exp": 3, "point": 0, "special": [29],"bigImage":"enemy_e164.png"},
	"e167": {"name": "付丧法师", "hp": 180, "atk": 14, "def": 1, "money": 0, "exp": 6, "point": 0, "special": [2, 29],"bigImage":"enemy_e167.png"},
	"e168": {"name": "炎响鬼", "hp": 92, "atk": 26, "def": 5, "money": 0, "exp": 6, "point": 0, "special": [],"bigImage":"enemy_e168.png"},
	"e171": {"name": "古战场跡", "hp": 185, "atk": 27, "def": 5, "money": 0, "exp": 7, "point": 0, "special": [],"bigImage":"enemy_e171.png"},
	"e190": {"name": "霜夜射手", "hp": 95, "atk": 28, "def": 4, "money": 0, "exp": 6, "point": 0, "special": [],"bigImage":"enemy_e190.png"},
	"e197": {"name": "樱吹玉", "hp": 65, "atk": 19, "def": 1, "money": 0, "exp": 3, "point": 0, "special": [45],"bigImage":"enemy_e197.png"},
	"e2": {"name": "小红玉", "hp": 36, "atk": 8, "def": 0, "money": 0, "exp": 1, "point": 0, "special": [],"bigImage":"enemy_e2.png"},
	"e222": {"name": "月光瀑", "hp": 160, "atk": 36, "def": 2, "money": 0, "exp": 7, "point": 0, "special": [57],"bigImage":"enemy_e222.png"},
	"e3": {"name": "小黑玉", "hp": 25, "atk": 10, "def": 0, "money": 0, "exp": 1, "point": 0, "special": [],"bigImage":"enemy_e3.png"},
	"e304": {"name": "土魔偶", "hp": 200, "atk": 8, "def": 0, "money": 0, "exp": 2, "point": 0, "special": [],"bigImage":"enemy_e304.png"},
	"e322": {"name": "冥界守卫", "hp": 180, "atk": 28, "def": 7, "money": 0, "exp": 8, "point": 0, "special": [55],"bigImage":"enemy_e322.png"},
	"e403": {"name": "幽幽子", "hp": 360, "atk": 180, "def": 0, "money": 0, "exp": 8, "point": 0, "special": [45], "bigImage": "005.png"},
	"e438": {"name": "返魂蝶", "hp": 120, "atk": 35, "def": 0, "money": 0, "exp": 6, "point": 0, "special": [],"bigImage":"enemy_e438.png"},
	"e439": {"name": "土灵使", "hp": 17, "atk": 28, "def": 0, "money": 0, "exp": 6, "point": 0, "special": 3,"bigImage":"enemy_e439.png"},
	"e440": {"name": "初级守卫", "hp": 100, "atk": 15, "def": 0, "money": 0, "exp": 3, "point": 0, "special": [16],"bigImage":"enemy_e440.png"},
	"e443": {"name": "古战场茗", "hp": 160, "atk": 26, "def": 6, "money": 0, "exp": 7, "point": 0, "special": [],"bigImage":"enemy_e443.png"},
	"e449": {"name": "冥府花", "hp": 160, "atk": 29, "def": 1, "money": 0, "exp": 6, "point": 0, "special": [],"bigImage":"enemy_e449.png"},
	"e46": {"name": "琥珀泪", "hp": 108, "atk": 26, "def": 3, "money": 0, "exp": 5, "point": 0, "special": [],"bigImage":"enemy_e46.png"},
	"e48": {"name": "小小蝠", "hp": 9, "atk": 21, "def": 0, "money": 0, "exp": 1, "point": 0, "special": 1,"bigImage":"enemy_e48.png"},
	"e49": {"name": "幽幽蝠", "hp": 45, "atk": 35, "def": 0, "money": 0, "exp": 4, "point": 0, "special": [1, 55],"bigImage":"enemy_e49.png"},
	"e66": {"name": "緋朱蔦", "hp": 85, "atk": 32, "def": 2, "money": 0, "exp": 7, "point": 0, "special": 4,"bigImage":"enemy_e66.png"},
	"e84": {"name": "魔法学徒", "hp": 45, "atk": 10, "def": 0, "money": 0, "exp": 2, "point": 0, "special": 2,"bigImage":"enemy_e84.png"},
	"e85": {"name": "暗法师", "hp": 75, "atk": 11, "def": 0, "money": 0, "exp": 3, "point": 0, "special": 2,"bigImage":"enemy_e85.png"},
	"e86": {"name": "樱法师", "hp": 45, "atk": 26, "def": 0, "money": 0, "exp": 3, "point": 0, "special": [2, 64],"bigImage":"enemy_e86.png"},
}
